/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./public/index.html', './src/**/*.{html,js,jsx,ts,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {},
    },
    plugins: [require('@tailwindcss/typography'), require('daisyui')],
    daisyui: {
        themes: [
            'aqua',
            'business',
            'corporate',
            'cyberpunk',
            'dark',
            'dim',
            'dracula',
            'forest',
            'garden',
            'light',
            'lofi',
            'night',
            'nord',
            'pastel',
            'retro',
            'sunset',
            'winter',
            'wireframe',
        ],
        darkTheme: 'dark',
        base: true,
        styled: true,
        utils: true,
        themeRoot: ':root',
    },
};
